from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, JSON
from sqlalchemy.orm import relationship
from app.core.database import Base

class Job(Base):
    __tablename__ = "jobs"

    id = Column(String, primary_key=True, index=True)
    my_id = Column(String, nullable=True)
    num = Column(Integer, nullable=True)
    description = Column(String, nullable=True)
    priority = Column(String, nullable=True)
    customer = Column(JSON, nullable=True)
    system_type = Column(String, nullable=True)  # "pure" or "hybrid"
    load_demand_kwh = Column(Float, nullable=True)
    peak_sun_hours = Column(Float, nullable=True)
    panel_capacity_kw = Column(Float, nullable=True)
    battery_capacity_kwh = Column(Float, nullable=True)
    inverter_capacity_kw = Column(Float, nullable=True)
    daily_output_kwh = Column(Float, nullable=True)
    excess_kwh = Column(Float, nullable=True)
    panel_cost_ksh = Column(Float, nullable=True)
    battery_cost_ksh = Column(Float, nullable=True)
    inverter_cost_ksh = Column(Float, nullable=True)
    installation_cost_ksh = Column(Float, nullable=True)
    total_cost_ksh = Column(Float, nullable=True)
    roi_years = Column(Float, nullable=True)
    system_efficiency = Column(Float, nullable=True)
    site = Column(String, nullable=True)
    equipment = Column(JSON, nullable=True)
    project = Column(JSON, nullable=True)
    type = Column(String, nullable=True)
    report_template = Column(String, nullable=True)
    created_by = Column(JSON, nullable=True)
    address_street = Column(String, nullable=True)
    address_province = Column(String, nullable=True)
    address_city = Column(String, nullable=True)
    address_zip = Column(String, nullable=True)
    address_country = Column(String, nullable=True)
    address = Column(String, nullable=True)
    address_complement = Column(String, nullable=True)
    contact_first_name = Column(String, nullable=True)
    contact_last_name = Column(String, nullable=True)
    contact_mobile = Column(String, nullable=True)
    contact_phone = Column(String, nullable=True)
    contact_email = Column(String, nullable=True)
    status = Column(String, nullable=True)
    public_link = Column(String, nullable=True)
    technician_id = Column(Integer, nullable=True)  # Foreign key to technicians
    scheduled_start = Column(DateTime, nullable=True)
    scheduled_end = Column(DateTime, nullable=True)
    actual_start = Column(DateTime, nullable=True)
    actual_end = Column(DateTime, nullable=True)
    created_by_customer = Column(Boolean, nullable=True)
    position = Column(JSON, nullable=True)
    custom_field_values = Column(JSON, nullable=True)
    date_created = Column(DateTime, nullable=True)
    date_modified = Column(DateTime, nullable=True)
    preferences = Column(JSON, nullable=True)
    technician_name = Column(String, nullable=True)
    technician_login = Column(String, nullable=True)
    job_type = Column(String, nullable=True)

    # Relationships
    technician = relationship("Technician", back_populates="jobs")
    predictions = relationship("Prediction", back_populates="job")